### ISSUE TITLE
Studbits MVP Release - Sprint 2: Polish Prototype 

### ISSUE THREAD

**Issue by alidcastano** [studbits/studbits#1]
## Overview

The goal is to release Studbits as soon as possible; this repo is a roadmap of the minimin amount of work that needs to be done to ship the first version.

Below are the `sprints` required for MVP release. All sprints start as an open discussion of a high-level goal that needs to be accomplished. When a sprint is started, it is given a name that conceptualizes its purpose.

I'm committing to completing *at least one tasks per day* for any item in the below sprints. My daily progress can be tracked via the `daily-scrum` entries in this repo. Each list taks will undeniably have other tasks that are associated with it creep up, so all extra activity can be tracked there.

All ideas that do not align with MVP focus will be added to the `backlog` below.

_I'll edit this list as I develop the idea, and there will also be issues that pop-up in the process, so I will make sure to handle those as well._

#### Raw Prototype - flesh out the idea in the front-end

First, I must develop the raw functionality of the core idea in front-end: 
- [x] Create note editor (with note editable title and mobiledoc body)
- [x] Allow creation of multiple note/editor instances in the same topic
- [x] Create topics with nested notes
- [x] Add dashboard preview of topics and notes
- [x] Create inline toolbar (a la medium) for note editor body
- [x] Add dropdown ability to notes
- [x] Add ability to chunk notes via flipcard
- [x] Add ability to toggle study and edit mode
- [x] Make flipcard edit/study modes (write as a cornell notes, study as a flashcard)
- [x] Add option to go fullscreen for each note

#### Polished Prototype - refine the front-end features

Then, I must style, fix, and enhance the little features that exist to make them usable:
- [ ] Polish topic editor/toolbar component 
  -  [ ] Allow ability to edit topic title
  - [x] Covert single display mode button to seperate but complementary write/study button views 
  - [x] Change labels to icons with toasters (e.g. fullscreen button and dropdown card)
  - [ ] Add tooltip to signal seperation from body
- [x] Polish editor toolbars
  - [x] Fix dynamic top positioning 
  - [x] Add hover toolbar for markup buttons 
  - [x] Add all section / card buttons to sticky toolbar
- [x] Polish editor note 
  - [x] Style `newNote` action button
  - [x] Improve fullscreen note view positioning and hide body toggle button 
  - [x] Make note title part of editor body (a la medium) to simplify interface 
  - [x] Create title proxy for when note is folded (since title is now part of now and will dissapear with it) 
  - [x] Standardize editor markup and section styling 
- [ ] Ehance chunk card 
  - [x] Create placeholder for stud and bit text 
  - [ ] Create write/read/study views 
  - [ ] Convert contenteditable into text area for stud and mobiledoc editor for bit
  - [x] Ref Mon Oct 9th / 10th for other work 
- [x] Create site navigation header 
- [x] Refactor and fix dashboard view 
- [x] Decide on and add color scheme 

####  Pending Sprints 

After, I must hookup the prototype to back-end API:
- [ ] Debounce expensive calls 
- [ ] Create new user
- [ ] Add new note
- [ ] Fetch all notes

Additionally, I must refactor and test the codebase: 
- [ ] Refactor pages into components
- [ ] Add e2e tests for key functionality (e.g. inline toolbar, edit/study mode, etc)

Lastly, I must prepare the prototype for deployment: 
- [x]  Create quick landing page
- [ ]  Add new user cues
   - [ ] Create new note
   - [ ] Create flipcard

## Backlog

MVP release or next release: 
- Make chunk width expand when active 
- Make it so that new chunks can actually be added between chunk cards 
- Add ability to create connections (`&`) between notes
- Ability to add tags (`#`) to notes 
- Ability to search all notes 
- Add fixed metabar for collection page so collection mode and other actions are always visible

Other important tasks: 

- Make toolbar behavior consistent 
  - Click on heading versus chunk produces same result 
- Make action buttons only appear on parent hover
- Add ability to create note between pages (a la Quizlet) 
- Allow reordering of sections
- Allow resizing of cards (e.g. cornell note studs)
- Add keyboard inputs for toolbar actions

Later releases: 
- Consider adding collections (i.e. group notes between topics)
- Add webclip/research view to left of topic/note and connection view to the right
- Add heading side anchor navigation (a la dropbox) in read mode 
- Add test mode (versus current read/study more) - one flashcard at a time plus points
- Add ability to use markdown

Someday later: 
- Ability to share notes
- Ability to fork other people's notes

**Comment by alidcastano** [comment]
Renamed it from "usable" to "polished" – more semantically appropriate :)

**Comment by alidcastano** [comment]
I skipped to developing the landing page yesterday because I wanted a better feel for the theme I was going for and how I was going to pitch Studbits.

**Comment by alidcastano** [comment]
Yesterday I also invested time styling dashboard header to get a better idea of theme / flow of the site. 

Today I'll focus again on what makes Studbtits unique: chunk cards and their different functionality in write and study modes.

**Comment by alidcastano** [comment]
Update: Deployed the landing page with EARLY working demo yesterday.

I've realized I need to iterate quickly and ship faster. I can't expect to ship my full vision for Studbits in the coming weeks, but I can start shipping a beautiful, simple editor from the beginning and slowly add features to it.

Going to reduce the tasks for this sprint so that I can move forward to hooking Studbits up to Blockstack and have a usable prototype (not just a demo) up and running.

**Comment by alidcastano** [comment]
Possibly going to create a new issue as work timeline and scope has shifted.
